apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: hyperfleet-local
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
